// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Meta$Llllvvuu from "../components/Meta.mjs";
import * as Layout$Llllvvuu from "../layouts/Layout.mjs";

function $$default(param) {
  return React.createElement(React.Fragment, undefined, React.createElement(Meta$Llllvvuu.make, {
                  title: "llllvvuu",
                  description: ""
                }), React.createElement(Layout$Llllvvuu.make, {
                  children: null
                }, React.createElement("h2", undefined, "Journey"), React.createElement("p", undefined, "In the beginning, I only cared about solving hard problems,\n        with no social purpose."), React.createElement("p", undefined, "As I began to seek social purpose in college,\n        I joined the organizing team for ", React.createElement("a", {
                          href: "https://ea.mit.edu/",
                          target: "_blank"
                        }, "MIT Effective Altruism."), " I still only considered direct work in\n        what would now be called \"deep tech\"\n        as a way to achieve human flourishing."), React.createElement("p", undefined, "Soon after I joined the \"real world\" (working on ", React.createElement("a", {
                          href: "https://www.getcruise.com/",
                          target: "_blank"
                        }, "self-driving cars, "), React.createElement("a", {
                          href: "https://www.soundhound.com/",
                          target: "_blank"
                        }, "speech recognition"), ", and ", React.createElement("a", {
                          href: "https://www.canarymedia.com/articles/solar/solar-software-synergy-aurora-acquires-folsom-labs",
                          target: "_blank"
                        }, "solar design and optimization"), "), I realized that social problems,\n        including ", React.createElement("a", {
                          href: "https://slatestarcodex.com/2014/07/30/meditations-on-moloch/",
                          target: "_blank"
                        }, "coordination problems"), ", were a huge bottleneck to flourishing.\n        I began scoping out a pivot to the social sciences."), React.createElement("p", undefined, "Before I could make a career move, DeFi summer happened.\n        No longer is it necessary to climb up the public policy ladder\n        to begin experimenting with policy - code is policy.\n        With cryptonetworks forming overnight,\n        I saw opportunity to test, within a much more open and agile environment,\n        theories from my own reading in social science and the new ideas of cryptoeconomics\n        and cryptogovernance."), React.createElement("p", undefined, "My first production will be meta: ", React.createElement("a", {
                          href: "https://atoms.org",
                          target: "_blank"
                        }, "coordination for research"), ", including research on coordination itself.")));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
