// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactKatex from "react-katex";
import * as Meta$Llllvvuu from "../components/Meta.mjs";
import * as Layout$Llllvvuu from "../layouts/Layout.mjs";
import * as Remark$Llllvvuu from "../components/Remark.mjs";
import * as NextMdxRemote from "next-mdx-remote";
import * as PostInfo$Llllvvuu from "../components/PostInfo.mjs";

var components = {
  h2: (function (param) {
      return React.createElement("h2", {
                  className: "text-xl mt-2"
                }, param.children);
    }),
  h3: (function (param) {
      return React.createElement("h3", {
                  className: "text-lg mt-1"
                }, param.children);
    }),
  ul: (function (param) {
      return React.createElement("ul", {
                  className: "list-disc list-inside my-1"
                }, param.children);
    }),
  "p.inlineCode": (function (param) {
      return React.createElement("code", {
                  className: "p-0.5 rounded-sm"
                }, param.children);
    }),
  pre: (function (param) {
      return React.createElement("pre", {
                  className: "overflow-auto p-2 my-2 rounded shadow"
                }, param.children);
    }),
  a: (function (param) {
      var href = param.href;
      return React.createElement("a", {
                  href: href,
                  target: href.startsWith("/") ? "" : "_blank"
                }, param.children);
    }),
  Remark: (function (param) {
      return React.createElement(Remark$Llllvvuu.make, {
                  children: param.children
                });
    }),
  IM: (function (param) {
      return React.createElement(ReactKatex.InlineMath, {
                  children: param.children
                });
    }),
  BM: (function (param) {
      return React.createElement("div", {
                  className: "overflow-auto"
                }, React.createElement(ReactKatex.BlockMath, {
                      children: param.children
                    }));
    }),
  sp: (function (param) {
      return " ";
    })
};

function $$default(props) {
  var frontMatter = props.frontMatter;
  var compiledSource = props.source.compiledSource;
  return React.createElement(React.Fragment, undefined, React.createElement(Meta$Llllvvuu.make, {
                  title: frontMatter.title,
                  description: frontMatter.description
                }), React.createElement(Layout$Llllvvuu.make, {
                  children: null
                }, React.createElement(PostInfo$Llllvvuu.make, {
                      frontMatter: frontMatter
                    }), React.createElement("main", undefined, React.createElement(NextMdxRemote.MDXRemote, {
                          compiledSource: compiledSource,
                          components: components
                        }))));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
