// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Meta$Llllvvuu from "../components/Meta.mjs";
import * as Layout$Llllvvuu from "../layouts/Layout.mjs";

function $$default(param) {
  return React.createElement(React.Fragment, undefined, React.createElement(Meta$Llllvvuu.make, {
                  title: "llllvvuu",
                  description: ""
                }), React.createElement(Layout$Llllvvuu.make, {
                  children: null
                }, React.createElement("h2", {
                      className: "text-xl font-serif"
                    }, "Unbundling Gamma: Proposal for ETH^2-PERP"), React.createElement("h3", {
                      className: "font-serif italic mb-2"
                    }, "2021-08-10"), React.createElement("p", undefined, "I assume that gamma is what many traders fundamentally want. The mathematically intuitive way to expose gamma is through the square of the underlying price.")));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
