// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Meta$Llllvvuu from "../components/Meta.mjs";
import * as Layout$Llllvvuu from "../layouts/Layout.mjs";
import * as PostInfo$Llllvvuu from "../components/PostInfo.mjs";

function $$default(props) {
  return React.createElement(React.Fragment, undefined, React.createElement(Meta$Llllvvuu.make, {
                  title: "llllvvuu",
                  description: ""
                }), React.createElement(Layout$Llllvvuu.make, {
                  children: Belt_Array.zip(props.filenames, props.frontMatters).map(function (param) {
                        var filename = param[0];
                        return React.createElement(PostInfo$Llllvvuu.make, {
                                    frontMatter: param[1],
                                    filename: filename,
                                    key: filename
                                  });
                      })
                }));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
