// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Meta$Llllvvuu from "../components/Meta.mjs";
import * as Layout$Llllvvuu from "../layouts/Layout.mjs";

function $$default(param) {
  return React.createElement(React.Fragment, undefined, React.createElement(Meta$Llllvvuu.make, {
                  title: "llllvvuu",
                  description: ""
                }), React.createElement(Layout$Llllvvuu.make, {
                  children: null
                }, React.createElement("h2", undefined, "Bio"), React.createElement("p", undefined, "Lawrence is a developer and technical entrepreneur\n        with a background in pure math, statistics, algorithms, systems, and finance.\n        He holds computer science and mathematics degrees from MIT and has been\n        a software engineer at ", React.createElement("a", {
                          href: "https://www.getcruise.com/",
                          target: "_blank"
                        }, "Cruise Automation, "), React.createElement("a", {
                          href: "https://www.soundhound.com/",
                          target: "_blank"
                        }, "SoundHound, "), "and Folsom Labs (", React.createElement("a", {
                          href: "https://www.canarymedia.com/articles/solar/solar-software-synergy-aurora-acquires-folsom-labs",
                          target: "_blank"
                        }, "acquired by Aurora Solar"), ")."), React.createElement("p", undefined, "Recent interests include a more social science and transdisciplinary mindset,\n        seeing ", React.createElement("a", {
                          href: "https://slatestarcodex.com/2014/07/30/meditations-on-moloch/",
                          target: "_blank"
                        }, "coordination problems"), " as a bottleneck to realizing humanity's global optimum. Along these lines, ", React.createElement("a", {
                          href: "https://atoms.org",
                          target: "_blank"
                        }, "Atoms"), " is a recent initiative focused on coordinating and resourcing research\n        using Web3 and cryptoeconomics.")));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
