// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Head from "next/head";

function Meta(Props) {
  var title = Props.title;
  var description = Props.description;
  return React.createElement(React.Fragment, undefined, React.createElement(Head, {
                  children: null
                }, React.createElement("title", undefined, title), React.createElement("meta", {
                      charSet: "utf-8"
                    }), React.createElement("link", {
                      href: "/favicon.ico",
                      rel: "shortcut icon"
                    }), React.createElement("meta", {
                      content: description,
                      name: "description"
                    }), React.createElement("meta", {
                      content: "summary_large_image",
                      name: "twitter:card"
                    }), React.createElement("meta", {
                      content: "@llllvvuu",
                      name: "twitter:creator"
                    }), React.createElement("meta", {
                      content: title,
                      property: "og:title"
                    }), React.createElement("meta", {
                      content: description,
                      property: "og:description"
                    }), React.createElement("meta", {
                      content: "website",
                      property: "og:type"
                    }), React.createElement("script", {
                      defer: true,
                      src: "/instantpage.js"
                    }), React.createElement("script", {
                      defer: true,
                      src: "https://www.googletagmanager.com/gtag/js?id=G-MBWQ2DW007"
                    }), React.createElement("script", {
                      dangerouslySetInnerHTML: {
                        __html: "window.dataLayer = window.dataLayer || [];\nfunction gtag(){dataLayer.push(arguments);}\ngtag('js', new Date());\ngtag('config', '" + "G-C9LL5WYTVN" + "');"
                      }
                    })));
}

var make = Meta;

export {
  make ,
  
}
/* react Not a pure module */
