// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Twitter from "@material-ui/icons/Twitter";

function PostInfo(Props) {
  var frontMatter = Props.frontMatter;
  var filename = Props.filename;
  var twitter = frontMatter.twitter;
  return React.createElement(React.Fragment, undefined, React.createElement("h2", undefined, filename !== undefined ? React.createElement("a", {
                        href: "/blog/" + filename
                      }, frontMatter.title) : frontMatter.title), React.createElement("h3", undefined, frontMatter.description), React.createElement("h4", {
                  className: "italic mb-2"
                }, frontMatter.date, twitter !== undefined ? React.createElement("a", {
                        className: "mx-1 text-blue-500",
                        href: twitter,
                        target: "_blank"
                      }, React.createElement(Twitter, {
                            fontSize: "small"
                          })) : React.createElement(React.Fragment, undefined)));
}

var make = PostInfo;

export {
  make ,
  
}
/* react Not a pure module */
