// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Remark(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: "p-2 border-l-8 border-blue-300 bg-blue-100 my-2\n      dark:border-yellow-600 dark:bg-yellow-800"
            }, children);
}

var make = Remark;

export {
  make ,
  
}
/* react Not a pure module */
