// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as React$1 from "@headlessui/react";

function ThemeSwitcher(Props) {
  var dark = Props.dark;
  var setDark = Props.setDark;
  return React.createElement("div", {
              className: "fixed top-4 right-4"
            }, React.createElement(React$1.Switch, {
                  checked: dark,
                  onChange: setDark,
                  className: (
                    dark ? "bg-blue-600" : "bg-gray-200"
                  ) + " relative inline-flex items-center h-6 rounded-full w-11\n    ease-in-out duration-200",
                  children: null
                }, React.createElement("span", {
                      className: "sr-only"
                    }, "Enable notifications"), React.createElement("span", {
                      className: (
                        dark ? "translate-x-6" : "translate-x-1"
                      ) + " inline-block w-4 h-4 transform bg-white rounded-full\n        ease-in-out duration-200"
                    })));
}

var make = ThemeSwitcher;

export {
  make ,
  
}
/* react Not a pure module */
